# Make a copy of this file named "config.yaml" and adjust it to your needs.

url: "https://mycompany.atlassian.net"
username: "john.doe@mycompany.com"
api_token: "(Generate a personal access token and put it here. Alternatively, delete this line and put it in the JIRA_CLI_API_TOKEN environment variable.)"

project_key: "(If an issue is named e.g. HOY-123, then put 'HOY' here)"
summary: "Sample issue"
issuetype: "Task"
assignee: "John Doe"
status: "In Progress"
description: |
  *Acceptance criteria:*

  * ...

  *Background:*
